name: End-to-end tests
on: [push]

env: 
  DISCORD_CLIENT_ID: ${{secrets.DISCORD_CLIENT_ID}}
  DISCORD_CLIENT_SECRET: ${{secrets.DISCORD_CLIENT_SECRET}}
  NEXT_AUTH_SECRET: ${{secrets.NEXT_AUTH_SECRET}}
  NEXTAUTH_URL: https://www.stemify2.net
  DISCORD_BOT_TOKEN: ${{secrets.DISCORD_BOT_TOKEN}}
  NEXTAUTH_SECRET: ${{NEXT_AUTH_SECRET}}

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run start
          wait-on: 'http://localhost:3000'