name: Deploy to prod
on:
  push:
    branches:
      - main

env: 
  DISCORD_CLIENT_ID: ${{secrets.DISCORD_CLIENT_ID}}
  DISCORD_CLIENT_SECRET: ${{secrets.DISCORD_CLIENT_SECRET}}
  NEXT_AUTH_SECRET: ${{secrets.NEXT_AUTH_SECRET}}
  NEXTAUTH_URL: https://www.stemify2.net
  DISCORD_BOT_TOKEN: ${{secrets.DISCORD_BOT_TOKEN}}
  NEXTAUTH_SECRET: ${{secrets.NEXT_AUTH_SECRET}}

  DATABASE_URL: ${{secrets.DATABASE_URL}}
  SPOTIFY_BASE64: ${{secrets.SPOTIFY_BASE64}}
  GOOGLE_CLIENT_EMAIL: ${{secrets.GOOGLE_CLIENT_EMAIL}}
  GOOGLE_PRIVATE_KEY: ${{secrets.GOOGLE_PRIVATE_KEY}}

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run start
          wait-on: 'http://localhost:3000'
  deploy:
    runs-on: ubuntu-latest
    needs: cypress-run
    steps:
      - uses: actions/checkout@v2
      #  your build commands
      # - run: |
      #    ng build --prod
      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional 
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  # Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} # Required 